[package]
name = "simd-rs"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>","Reinier Maas <reiniermaas@hotmail.com>"]

[dependencies]
simd = { git = "https://github.com/huonw/simd" }
